name: ci

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tmayweather/clutch-ui, tmayweather/clutch-api
          tags: |
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save frontend and backend tags to files
        run: |
          echo "${{ steps.meta.outputs.tags.frontend }}" > frontend-tags.txt
          echo "${{ steps.meta.outputs.tags.backend }}" > backend-tags.txt

      - name: Upload Docker image tags as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-tags
          path: |
            frontend-tags.txt
            backend-tags.txt


      - name: Trigger workflow in argocd-test
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: tmayweather/argocd-test
          workflow: update-image.yaml


