name: ci

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tmayweather/clutch-ui, tmayweather/clutch-api


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Call manifest repo
        uses: actions/checkout@v4
        with:
          repository: tmayweather/argocd-test
          ref: main
          path: projects/overlays/dev

      - name: Update backend image in argocd
        run: |
          kustomize edit set image tmayweather/clutch-api:${{ steps.meta_backend.outputs.tags }}
          git add kustomize.yaml
          git commit -m "Update backend to version ${{ steps.meta_backend.outputs.tags }}"
          git push

      - name: Update frontend image in argocd
        run: |
          kustomize edit set image tmayweather/clutch-ui:${{ steps.meta_frontend.outputs.tags }}
          git add kustomize.yaml
          git commit -m "Update frontend to version ${{ steps.meta_frontend.outputs.tags }}"
          git push

