name: ci

on:
  push:
    branches:
      - master


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: tmayweather/clutch-ui, tmayweather/clutch-api
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install semver
        run: |
          curl -LO https://github.com/fsaintjacques/semver-tool/archive/v3.0.0.tar.gz
          tar xzf v3.0.0.tar.gz
          sudo mv semver-tool-3.0.0/semver /usr/local/bin/
          rm -f v3.0.0.tar.gz
        shell: bash

      - name: Get the tag name
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/*/}

      - name: Increment the tag
        id: semver
        run: echo ::set-output name=NEW_TAG::$(semver -c -i minor ${{ steps.tag.outputs.TAG }})   

      - name: Build and push backend
        working-directory: backend
        run: |
          docker build -t tmayweather/clutch-api:${{ steps.semver.outputs.NEW_TAG }} .
          docker push tmayweather-clutch-api:${{ steps.semver.outputs.NEW_TAG }}

      - name: Build and push frontend
        working-directory: frontend
        run: |
          docker build -t tmayweather/clutch-ui:${{ steps.semver.outputs.NEW_TAG }} .
          docker push tmayweather-clutch-ui:${{ steps.semver.outputs.NEW_TAG }}

      # - name: Build and push frontend
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: frontend
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      # - name: Build and push backend
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: backend
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}


      # - name: Get manifest repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: tmayweather/argocd-test
      #     ref: main
      #     sparse-checkout: |
      #       argocd

      # - name: Update backend and frontend image in argocd
      #   working-directory: ./argocd/projects/overlays/dev
      #   run: |
      #     kustomize edit set image tmayweather/clutch-ui=${{ steps.meta.outputs.tags }} .
      #     git add .
      #     git commit -m "Update clutch to version ${{ steps.meta.outputs.tags }}"
      #     git push



