name: ci

on:
  push:
    branches:
      - master

    tags:
      - 'v*' 


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tmayweather/clutch-ui
          tags: |
            type=sha
            type=ref,event=tag
            type=ref,event=pr
          flavor: latest=auto
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Get manifest repo
        uses: actions/checkout@v4
        with:
          repository: tmayweather/argocd-test
          ref: main
          sparse-checkout: |
            argocd

      - name: Set Git user
        run: |
          git config --global user.email "tnea.mayeather@gmail.com"
          git config --global user.name "tmayweather"

      - name: Update backend and frontend image in argocd
        working-directory: ./argocd/projects/overlays/dev
        run: |
          kustomize edit set image ${{ steps.meta.outputs.tags }}
          git add .
          git commit -m "Update clutch to version ${{ steps.meta.outputs.tags }}"
          git push



