name: ci

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get latest Docker Hub tag
        id: get-tag
        run: |
          latest_tag=$(curl -s -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" https://hub.docker.com/v2/repositories/yourusername/yourrepository/tags/?page_size=100 | jq -r '.results[].name' | grep -E 'v[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          next_version=$(echo $latest_tag | awk -F '.' '{printf "v%.1f", $NF + 0.1}')
          echo "::set-output name=tag::$next_version"

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: tmayweather/clutch-ui, tmayweather/clutch-api
      #     tags: |
      #       type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tmayweather/clutch-ui:${{ steps.get_tag.outputs.tag }}
            tmayweather/clutch-ui:latest
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Build and push backend
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: backend
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}


      # - name: Get manifest repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: tmayweather/argocd-test
      #     ref: main
      #     sparse-checkout: |
      #        argocd

      # - name: Update backend and frontend image in argocd
      #   working-directory: ./argocd/projects/overlays/dev
      #   run: |
      #     kustomize edit set image tmayweather/clutch-ui=tmayweather/clutch-ui:${{ github.sha }} .
      #     git add .
      #     git commit -m "Update clutch to version ${{ steps.meta.outputs.tags }}"
      #     git push



